/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package number_game;

import java.util.Random;

/**
 *
 * @author pande
 */
public class home extends javax.swing.JFrame {

    String na;
    String tfval="<html>";
    int move=5;
     Random ran= new Random();
     int gamevalue= ran.nextInt(100);
    /**
     * Creates new form home
     */
    public home(String na) {
        this.na= na;
        initComponents();
        setval();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        choose = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        show = new javax.swing.JLabel();
        tryagain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 53, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Serif", 2, 48)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 830, 60));

        choose.setFont(new java.awt.Font("Yu Gothic UI Light", 2, 24)); // NOI18N
        choose.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.add(choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 550, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 150));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel2.add(tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 380, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Enter Your Guess :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 360, 40));

        btn.setBackground(new java.awt.Color(0, 0, 0));
        btn.setForeground(new java.awt.Color(255, 255, 255));
        btn.setText("LOCK IT");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel2.add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 140, 30));

        show.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 20)); // NOI18N
        show.setForeground(new java.awt.Color(0, 51, 51));
        jPanel2.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 650, 310));

        tryagain.setBackground(new java.awt.Color(0, 0, 0));
        tryagain.setForeground(new java.awt.Color(255, 255, 255));
        tryagain.setText("Try Again");
        tryagain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryagainActionPerformed(evt);
            }
        });
        jPanel2.add(tryagain, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, 140, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1100, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        check();
            
    }//GEN-LAST:event_btnActionPerformed

    private void tryagainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryagainActionPerformed
        again();
    }//GEN-LAST:event_tryagainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home("User").setVisible(true);
            }
        });
    }
    
    void setval()
    {
        name.setText("WELCOME!!!  "+na+"  To Our Game");
        choose.setText("Choose a number between 1-100");
        setTitle("NUMBER GUSSING GAME");
        tryagain.setVisible(false);
    }

    void check()
    {
        int num;
      
             String n="";
            n= tf.getText();
            num= Integer.parseInt(n);
            if(move==0)
            {
                show.setText("You Lost Try Again");
                btn.setEnabled(false);
                newtry();
            }
            else {
            if(num>gamevalue)
            {
                tfval= tfval + "The Number is LESS The Guess Number (" +move+"  Left) Your Value = "+ num +"<br>";
            }
            else if(num<gamevalue)
            {
                tfval= tfval + "The Number is MORE The Guess Number (" +move+"  Left) Your Value = "+ num +"<br>";
            }
            else if(num == gamevalue)
            {
                tfval= tfval + "<br>CONGRATS!!!!!! You Won The Game..................... <br></html> ";
                tf.setText("");
                move--;
                show.setText(tfval);
                btn.setEnabled(false);
                newtry();
            }
            tf.setText("");
            move--;
            show.setText(tfval);
            
            }
    }
    
    
    void newtry()
    {
        tryagain.setVisible(true);
    }
    
    
    void again()
    {
        setVisible(false);
        new home(na).setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JLabel choose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel show;
    private javax.swing.JTextField tf;
    private javax.swing.JButton tryagain;
    // End of variables declaration//GEN-END:variables
}
